remote_theme: pmarsceill/just-the-docs
title: i5
description: The i5 programming language
baseurl: "/"
url: "https://i5-lang.github.io"
search_enabled: true
aux_links:
  "iota5 on GitHub":
    - "//github.com/i5-lang/i5"
plugins:
  - jekyll-seo-tag
